# Generated by Django 5.0 on 2024-02-18 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Intrudection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Myprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='private/images/')),
                ('bio', models.CharField(max_length=75)),
                ('link', models.URLField(blank=True)),
                ('link_2', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('text', models.TextField(max_length=10000, verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('text_2', models.TextField(blank=True, max_length=10000, verbose_name='Second Text')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text_3', models.TextField(blank=True, max_length=10000, verbose_name='Third Text')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_2', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'indexes': [models.Index(fields=['created_at'], name='main_post_created_84fc03_idx')],
            },
        ),
    ]
