# Generated by Django 5.0 on 2024-02-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_2',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Second Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_3',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Third Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
