# Generated by Django 5.0 on 2024-02-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myprofile_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intrudection',
            new_name='Introduction',
        ),
    ]
