# Generated by Django 5.0 on 2024-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_image_alter_post_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/'),
        ),
    ]
