# Generated by Django 5.0 on 2024-02-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='bio',
        ),
    ]
