# Generated by Django 5.0 on 2024-03-19 23:12

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='category',
            field=models.CharField(choices=[('PI', 'Page Introduction'), ('PR', 'Project Introduction'), ('PO', 'Post Introduction')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 23, 10, 56, 451777, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 23, 10, 56, 451777, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 3, 19, 23, 10, 56, 451777, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 23, 10, 56, 451777, tzinfo=datetime.timezone.utc), verbose_name='Updated At'),
        ),
    ]
